### PR TITLE
More instances of orders

### PR DESCRIPTION
**Pull request by plt-amy**
Includes poset facts for `Nat`/`Int` and @mmcqd's work on poset constructions. Also includes definition of total orders + proof that these have meets and joins.

"More instances of orders", they say, in the middle of rewriting everything to do with integers... The initial ring is still using the higher-inductive ℤ, but everything else is ported (there wasn't much).

### CODE REVIEW

**Comment by Lavenza** [comment]
[Pull request preview](https://preview.1lab.dev/327)

**Comment by favonia** [comment]
Is `+ℤ-injectiver` used anywhere? It's needed in our own development, but it seems a bit strange in the generic library without `+ℤ-injectivel`.

**Comment by plt-amy** [comment]
I added it only because it was part of the `Mugen.Data.Int` module I was upstreaming; there's not much about integers in the 1Lab yet, so it's not used. I guess I could add `+ℤ-injectivel` as well

**Review by Lavenza — APPROVED** [review]

**Comment by favonia** [comment]
Speaking of upstreaming, let me note here for the record that the credit of the original file belongs to @TOTBWF and me, BUT @plt-amy has pretty much rewritten the whole thing from scratch.

**Pull request merged**
