### PR TITLE
`^op` → `\op` in LaTeX

### PR DESCRIPTION
**Pull request by ncfavier**

### CODE REVIEW

**Comment by SquidDev** [comment]
I don't think `\op` is a valid LaTeX term. At least KaTeX and MathJax don't appear to support it (you get $\op$).

**Comment by plt-amy** [comment]
It's one of our macros

**Comment by plt-amy** [comment]
Thanks for the contribution! I keep messing this up haha

**Comment by SquidDev** [comment]
Ahh, thanks! Sorry, I'm a plonker.

**Pull request merged**
